This is makeindex, version 2.15 [TeX Live 2013] (kpathsea + Thai support).
Scanning style file ./ClassicThesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file ClassicThesis.acn....done (192 entries accepted, 0 rejected).
Sorting entries.....done (1554 comparisons).
Generating output file ClassicThesis.acr....done (82 lines written, 0 warnings).
Output written in ClassicThesis.acr.
Transcript written in ClassicThesis.alg.
