---
title: "Ayudita"
author: "Antonio Álvarez Caballero"
date: "11 de diciembre de 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(ggplot2)
require(reshape2)

formatter1000 <- function(x){ 
    x/1000000
}
```

# Holis

```{r}
CPU9 <- read.csv("999/999CPU.csv")
GPU9 <- read.csv("999/999GPU.csv")
m9 <- merge(CPU9,GPU9)
colnames(m9) <- c("Pixels","CPU","GPU")

CPU1 <- read.csv("0001/0001CPU.csv")
GPU1 <- read.csv("0001/0001GPU.csv")
m1 <- merge(CPU1,GPU1)
colnames(m1) <- c("Pixels","CPU","GPU")
```


```{r}
# EscandiMorning <- melt(m, id.vars = "Pixels")
# 
# ggplot(EscandiMorning, aes(Pixels, value, color = "red")) +
#   geom_line() +
#   ylab("Time") +
#   theme(legend.title=element_blank())

speedup1 <- data.frame(Pixels = m1$Pixels,
                       SpeedUp = m1$CPU / m1$GPU)

speedup9 <- data.frame(Pixels = m9$Pixels,
                       SpeedUp = m9$CPU / m9$GPU)

# ggplot(speedup1, aes(Pixels,)) +
#   geom_line(aes(y = SpeedUp, colour = "Schwarzschild")) + 
#   geom_line(aes(data = speedup9, colour = "Kerr")) +
#   ylab("Speed up") +
#   xlab("Image megapixels") +
#   ggtitle("Parallel code speed up") +
#   scale_x_continuous(labels = formatter1000)
  #geom_smooth(method = "lm",formula = y ~ log(x))

# (plot2 <- ggplot(NULL, aes(v, p)) + 
#       geom_point(data = df1) +
#       geom_step(data = df2)
# )
```

```{r}
ggplot() + 
  geom_line(data=speedup1, aes(x=Pixels, y=SpeedUp, colour='Spin = 0.0001')) +
  geom_line(data=speedup9, aes(x=Pixels, y=SpeedUp, colour='Spin = 0.999')) +
  ylab("Speed up") +
  xlab("Image megapixels") +
  ggtitle("Parallelized code speed up") +
  scale_x_continuous(labels = formatter1000) +
  theme(legend.title=element_blank())

ggsave("../../../../Documentation/Report/gfx/speedup.png")
```

```{r}
data <- read.csv("../../Graphs/stepradiusiter2.csv")
data$Step <- abs(data$Step)

data$Step <- (data$Step - min(data$Step))/(max(data$Step) - min(data$Step))
data$Radius <- (data$Radius - min(data$Radius))/(max(data$Radius) - min(data$Radius))


# data$Step <- scale(data$Step, center = min(data$Step), scale = max(data$Step) - min(data$Step))
# data$Radius <- scale(data$Radius, center = min(data$Radius), scale = max(data$Radius) - min(data$Radius))


# data$Step <- abs(data$Step)
ggplot(data, aes(Iteration)) +
  ylab("") +
  # ggtitle("Automatic step computation") +
  geom_line(aes(y = Radius, colour="Normalized radius")) +
  geom_line(aes(y = Step, colour="Normalized step")) +
  theme(legend.title=element_blank())

# ggsave("../../../../Documentation/Report/gfx/stepradius2.png")
```


```{r}
data <- read.csv("../../Graphs/iter_paso_r_theta_kretchman.csv")
data$Step <- abs(data$Step)

data$Step <- (data$Step - min(data$Step))/(max(data$Step) - min(data$Step))
data$R <- (data$R - min(data$R))/(max(data$R) - min(data$R))
data$Theta <- (data$Theta - min(data$Theta))/(max(data$Theta) - min(data$Theta))
data$Kretchmann <- (data$Kretchmann - min(data$Kretchmann))/(max(data$Kretchmann) - min(data$Kretchmann))


ggplot(data, aes(Iteration)) +
  ylab("") +
  # ggtitle("Automatic step computation") +
  geom_line(aes(y = R, colour="Normalized radius")) +
  geom_line(aes(y = Step, colour="Normalized step")) +
  geom_line(aes(y = Theta, colour="Normalized theta")) +
  geom_line(aes(y = Kretchmann, colour="Normalized\nKretschmann")) +
  theme(legend.title=element_blank())


ggsave("../../../../Documentation/Report/gfx/kretschmann.png")

```


```{r}
points <- read.csv("../../Graphs/points.csv")

require(Bessel)
analytic <- AiryB(points$X)

data <- data.frame(x = points$X, airy=analytic, rk=points$Y)

ggplot(data, aes(x)) +
  xlab("") +
  ylab("") +
  # ggtitle("Automatic step computation") +
  geom_line(aes(y = airy, colour="Analytic expression"), size=0.3) +
  geom_point(aes(y = rk, colour="Runge-Kutta solution"), size=0.2) +
  xlim(-9,2) +
  ylim(-0.5,1.5) +
  theme(legend.title=element_blank())

ggsave("../../../../Documentation/Report/gfx/analytic.png", width=10)

```





















